Feature/dd20cleaner basecode
energinet-singularity/conduck pull request #8
Opened 2022-04-05 13:35 UTC by CodeWitten

**Description of your changes**

Category:

- [x] New Feature
- [ ] Bugfix
- [ ] Documentation update

Checklist:

- [x] I have bumped all relevant version numbers
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my changes if this is needed
- [ ] I have described my changes in the "description of your changes" field
- [ ] I have tested this change on a running cluster 
- [x] I have created/corrected automated tests related to the changes, if possible/necessary
- [ ] I have checked that new and existing unit tests pass locally with my changes
- [x] I have squashed commits if necessary

2022-04-06 11:35 UTC, swedchef requested changes
Very nice code. I did not check pandas handled the frames as expected, but it looks fine. I have some minor comments and a few structural issues that might need to be taken up as a team - you decide.

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +        sys.exit(1)
I would suggest using 'raise' in stead of manually exiting. That way you don't have to import the sys module for just exiting, and the 'raise' will call a system exit anyway if unhandled. But the 'clever' thing is that i can actually be handled higher up in the stack. That way you will be using the built-in error/exception system and your function will survive being called within a 'try/except' in case someone actually wants to handle any errors "higher up".

```suggestion
        raise
```
or 
````suggestion
        raise IOError("File not found or incorrectly formatted") from e
````

The above suggestions are examples of how it COULD be done - ONE of them should be selected, or a similar approach. The first suggestion will just re-raise the exception that happened - the second suggestion will add another exception to the stack (giving more information, generally).

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +            sys.exit(1)
See previous comment on sys.exit vs raise

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +            sys.exit(1)
See previous comment on sys.exit vs raise

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +    The soruce data is DD20, which has a non standard format, why costumized cleaning and extraction from it is needed.
```suggestion
    The source data is DD20, which has a non-standard format, why customized cleaning and extraction from it is needed.
```

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +        Pandas dataframe, whcih will contain the follwing columns for each line in DD20:
```suggestion
        Pandas dataframe, which will contain the following columns for each line in DD20:
```

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +        # Select only rows where line name are pesent, by removing rows wtih null value and rows not containing "-"
```suggestion
        # Select only rows where line name are present, by removing rows with null value and rows not containing "-"
```

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +        # make list os conductor type per line
```suggestion
        # make list of conductor type per line
```

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +        restrictive_component_limits = [dataframe[dataframe[DD20_LINENAME_COL_NM].str.contains(line_name)][DD20_COLUMNS_COMPONENT_RESTICT].min(skipna=True).min(skipna=True)
'min()' two times on same data?

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +        # make lists of restrictive limits for cable (continious, 15M, 1H and 40H)
```suggestion
        # make lists of restrictive limits for cable (continuous, 15M, 1H and 40H)
```

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +        sys.exit(1)
See previous comment on sys.exit vs raise

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +        log.exception(f"Parsing data  failed with message: '{e}'.")
```suggestion
        log.exception(f"Parsing data failed with message: '{e}'.")
```

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +    log.info("Doing it..")
Dirty piece of code!

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +    print(condutor_data)
```suggestion
    conductor_data = extract_conducter_data_from_dd20(dataframe=dd20_dataframe)
    print(conductor_data)
```

2022-04-06 11:35 UTC, swedchef commented on app/my_script.py
> +DD20_40H_COL_NM = '40 timer'
I am not sure i have a good argument, but for some reason i dislike having CONST as global and set here when they are not shared between functions. Especially as you actually specify them when calling the function (and thereby do not use them as global). I get that they will be faster to find/access if you need to change them.. But.. Well.. My spidey-senses are tingling.. !

2022-04-07 08:27 UTC, CodeWitten commented on app/my_script.py
> +def convert_voltage_level_to_letter(voltage_level: float) -> str:
good point. Actually in the data kv wil alway be an interger, so no point in using float :)

2022-04-07 08:35 UTC, CodeWitten commented on app/my_script.py
> +DD20_40H_COL_NM = '40 timer'
i agree. good point. They are moved into functions where they are actually used.

2022-04-07 08:37 UTC, CodeWitten commented on chart/values.yaml
>    repository: ghcr.io/energinet-singularity/<repo-name>/energinet-singularity/<image-name>
check. Will do it after merge since the repo need renaming.

2022-04-07 08:38 UTC, CodeWitten commented on app/my_script.py
> +logging.getLogger().setLevel(logging.INFO)
you are correct. moved!

2022-04-07 11:07 UTC, CodeWitten commented on tests/test_script.py
> +# TODO: how to test function which does not return but sys.exit(1)?
thx for tip. now using raise.

2022-04-07 11:32 UTC, CodeWitten commented on app/my_script.py
> +        restrictive_component_limits = [dataframe[dataframe[DD20_LINENAME_COL_NM].str.contains(line_name)][DD20_COLUMNS_COMPONENT_RESTICT].min(skipna=True).min(skipna=True)
The reason is that multiple rows can be returned. First min is of rows, next min is of columns. I have to re-write the code due to DD20 format changes. I will look into making the filtering more readable as i myself does not like the syntax readability, eventhoug it works :)

2022-04-07 11:38 UTC, swedchef submitted a review, later dismissed
Brilliant!

2022-04-07 12:37 UTC, swedchef approved these changes
Nice done - atomic commit and all! 👯‍♂️

2022-04-07 12:41 UTC, merged